title: 3D Building Indoor-Outdoor Dataset
description: A website for 3D BIO Dataset
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Github: https://github.com/biodataset/biodataset
